
language: android
jdk:
    - oraclejdk8
android:
    components:
        - tools
        - platform-tools
        - build-tools-26.0.2
        - android-25
        - android-21
        - extra-android-m2repository
        - extra-android-support

script: ./gradlew check
